[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"
optimizer = true
optimizer_runs = 1000000

[profile.ci]
verbosity = 4

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = true

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[fuzz]
runs = 1000

[invariant]
runs = 1000
depth = 100
fail_on_revert = true
